--Quản lý cuộc hẹn
--view Cuoc Hen
use QuanLyPhongKhamNhaKhoa

GO
CREATE OR ALTER PROCEDURE p_ViewCuocHenTimeRange @TIME1 DATETIME, @TIME2 DATETIME, @MANS VARCHAR(10)
AS
BEGIN
	IF NOT EXISTS (SELECT * FROM NhaSi WHERE NhaSi.MA LIKE @MANS)
	BEGIN
		RAISERROR(N'NHA SĨ KHÔNG TỒN TẠI',14,1)
	END
	ELSE
	BEGIN
		SELECT * FROM CuocHen WHERE CuocHen.MANHASI LIKE @MANS AND CuocHen.ThoiGian BETWEEN @TIME1 AND @TIME2
	END

END
GO
CREATE OR ALTER PROCEDURE p_ViewDieuTriTimeRange @TIME1 DATETIME, @TIME2 DATETIME, @MANS VARCHAR(10)
AS
BEGIN
	IF NOT EXISTS (SELECT * FROM NhaSi WHERE NhaSi.MA LIKE @MANS)
	BEGIN
		RAISERROR(N'NHA SĨ KHÔNG TỒN TẠI',14,1)
	END
	ELSE
	BEGIN
		SELECT * FROM DieuTri WHERE DieuTri.MANHASI LIKE @MANS AND DieuTri.NgayDtr BETWEEN @TIME1 AND @TIME2
	END

END
